version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"  # Alterar a porta mapeada para 5432
