"""init_db

Revision ID: 9ba94ac73bed
Revises:
Create Date: 2025-03-19 16:38:55.829233

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ba94ac73bed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("pk_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "centro_treinamento",
        sa.Column("pk_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=20), nullable=False),
        sa.Column("endereco", sa.String(length=60), nullable=False),
        sa.Column("proprietario", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "atleta",
        sa.Column("pk_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=50), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("idade", sa.Integer(), nullable=False),
        sa.Column("peso", sa.Float(), nullable=False),
        sa.Column("altura", sa.Float(), nullable=False),
        sa.Column("sexo", sa.String(length=1), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("centro_treinamento_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("cpf ~ '^[0-9]+$'", name="cpf_numeric_check"),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categoria.pk_id"],
        ),
        sa.ForeignKeyConstraint(
            ["centro_treinamento_id"],
            ["centro_treinamento.pk_id"],
        ),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("atleta")
    op.drop_table("centro_treinamento")
    op.drop_table("categoria")
    # ### end Alembic commands ###
